### PR TITLE
Us#52 dev

### PR DESCRIPTION
**Pull request by mrgutie8**
Changes merging to dev

- delete user test with stubs
- reactivate user test with stubs

### CODE REVIEW

**Review by apassett — CHANGES_REQUESTED** [review]
response_json and response variable misspelled beginning on line 77.

**Comment by mrgutie8** [comment]
> response_json and response variable misspelled beginning on line 77.

got this fixed

**Comment by mrgutie8** [comment]
> response_json and response variable misspelled beginning on line 77.

got this fixed

**Review by apassett — APPROVED** [review]
Good to merge.

**Pull request merged**
